
package webbonusgx;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSAcumuPx", targetNamespace = "WebBonusGX", wsdlLocation = "http://200.62.147.188:8080/primax_des/servlet/awsacumupx?wsdl")
public class WSAcumuPx
    extends Service
{

    private final static URL WSACUMUPX_WSDL_LOCATION;
    private final static WebServiceException WSACUMUPX_EXCEPTION;
    private final static QName WSACUMUPX_QNAME = new QName("WebBonusGX", "WSAcumuPx");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://200.62.147.188:8080/primax_des/servlet/awsacumupx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSACUMUPX_WSDL_LOCATION = url;
        WSACUMUPX_EXCEPTION = e;
    }

    public WSAcumuPx() {
        super(__getWsdlLocation(), WSACUMUPX_QNAME);
    }

    public WSAcumuPx(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSACUMUPX_QNAME, features);
    }

    public WSAcumuPx(URL wsdlLocation) {
        super(wsdlLocation, WSACUMUPX_QNAME);
    }

    public WSAcumuPx(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSACUMUPX_QNAME, features);
    }

    public WSAcumuPx(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSAcumuPx(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSAcumuPxSoapPort
     */
    @WebEndpoint(name = "WSAcumuPxSoapPort")
    public WSAcumuPxSoapPort getWSAcumuPxSoapPort() {
        return super.getPort(new QName("WebBonusGX", "WSAcumuPxSoapPort"), WSAcumuPxSoapPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSAcumuPxSoapPort
     */
    @WebEndpoint(name = "WSAcumuPxSoapPort")
    public WSAcumuPxSoapPort getWSAcumuPxSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("WebBonusGX", "WSAcumuPxSoapPort"), WSAcumuPxSoapPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSACUMUPX_EXCEPTION!= null) {
            throw WSACUMUPX_EXCEPTION;
        }
        return WSACUMUPX_WSDL_LOCATION;
    }

}
